---
- name: Install docker and required s/w's
  hosts: all
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    - name: Download docker script and execute it and also install docker-py 
      shell: "{{item}}"
      with_items:
        - curl -fsSL https://get.docker.com -o get-docker.sh
        - sh get-docker.sh
        - pip3 install docker-py
