---
- name: Download docker images
  hosts: all
  tasks:
    - name: Pull docker images
      docker_image:
        name: "{{item}}"
        source: pull
      with_items:
        - tomee
        - ubuntu
        - mariadb
        - mysql
