---
- name: Install s/w's based on OS version
  hosts: all
  tasks:
    - name: Install tree using apt
      apt:
        name: tree
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install tree using yum
      yum:
        name: tree
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"

