---
- name: Copy tomcat-users.xml file
  copy:
    src: "{{file1}}"
    dest: "{{dest1}}"
- name: Change port of tomcat from 9090 to 8080
  replace:
    regexp: "{{port1}}"
    replace: "{{port2}}"
    path: "{{path1}}"
  notify: Check url response
...
